name: Build EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係インストール
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: EXE ファイルをビルド
        run: |
          pyinstaller --onefile testadd.py

      - name: 成果物をアップロード
        uses: actions/upload-artifact@v4
        with:
          name: exe-file
          path: dist/testadd.exe
